#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLEAN="$DIR/clean"

if [ "$#" -ne 1 ]; then
    echo "Need to give path of git repo"
    exit 1
fi

cat <<EOF >> $1/.git/config

[filter "git_clean"]
       clean = $CLEAN
       required
EOF

cat <<EOF >> $1/.git/info/attributes

* filter=git_clean
EOF
